<?php namespace ProcessWire;

    /**
     * Processwire module for generating srcset markup.
     * by Roland Toth (tpr)
     *
     * ProcessWire 3.x
     * Copyright (C) 2011 by Ryan Cramer
     * Licensed under GNU/GPL v2, see LICENSE.TXT
     *
     * http://www.processwire.com
     * http://www.ryancramer.com
     *
     */

/**
 * Class MarkupSrcSet
 *
 * @package ProcessWire
 */
class MarkupSrcSet extends WireData implements Module, ConfigurableModule {

    public $configData;

    /**
     * Basic information about module
     */
    public static function getModuleInfo() {
        return array(
            'title'     => 'Markup SrcSet',
            'summary'   => __('Generate srcset and bgset markup.', __FILE__),
            'href'      => 'https://processwire.com/talk/topic/12981-markupsrcset/',
            'version'   => 4,
            'author'    => 'Roland Toth',
            'autoload'  => true,
            'singular'  => true,
            'permanent' => false,
            'icon'      => 'cubes'
        );
    }

    /**
     * Default configuration for module
     *
     */
    static public function getDefaultData() {
        return array(
            "breakpoints"      => '360w 720w 990w 1220w',
            "imageSets"        => '',
            "addLazyloadClass" => 1,
            "loadScripts"      => 1,
            "useSrcSetAttr"    => 0
        );
    }

    public function __toString() {
        return __CLASS__;
    }


    /**
     * Hooks and global functions.
     *
     * @throws WireException
     */
    public function ready() {

        $this->configData = $this->wire('modules')->getModuleConfigData($this);

        $this->addHookBefore('Page::render', $this, 'storeImageSets');

        $this->addHook("Pageimage::srcset", $this, "getSrcSet");
        $this->addHook("Pageimage::bgset", $this, "getBgSet");

        if (isset($this->configData['loadScripts']) && $this->configData['loadScripts'] != "") {
            $this->addHookAfter('Page::render', $this, 'loadScripts');
        }

    }


    /**
     * Function to render srcset markup.
     *
     * @param $event
     *
     * @return mixed
     */
    public function getSrcSet(HookEvent $event) {
        $event->return = $this->getSrcSetMarkup($event->object, $event->arguments, 'srcset');
    }


    /**
     * Function to render bgset markup.
     *
     * @param $event
     *
     * @return mixed
     */
    public function getBgSet(HookEvent $event) {
        $event->return = $this->getSrcSetMarkup($event->object, $event->arguments, 'bgset');
    }

    /**
     * Generates srcset or bgset markup.
     *
     * @param $img
     * @param $args
     * @param string $mode
     *
     * @return bool|string
     */
    public function getSrcSetMarkup($img, $args, $mode = 'srcset') {

        $markup = "";
        $srcSetTag = "data-srcset";

        $classes = null;

        if (isset($args[1])) {
            if (boolval($args[1])) {
                // class is set but it's not empty or false
                $classes = $args[1];
            }
        } else {
            if (isset($this->configData['addLazyloadClass']) && $this->configData['addLazyloadClass'] === 1) {
                $classes = 'lazyload';
            }
        }

        $sizeName = isset($args[0]) ? $args[0] : null;
        $pwImageResizeOptions = isset($args[2]) ? $args[2] : null;
        $flags = isset($args[3]) ? $args[3] : null;

        if (
            !($img instanceof Pageimage) ||
            !isset($sizeName) ||
            empty($sizeName)
        ) {
            return false;
        }

        $srcset = array();
        $breakpoints = wire('modules')->MarkupSrcSet->breakpoints;
        $sizeArray = wire('config')->imageSets[$sizeName];

        if (isset($this->configData['useSrcSetAttr']) && $this->configData['useSrcSetAttr'] === 1) {
            $srcSetTag = "srcset";
        }

        // get data-sizes value from the highest breakpoint
        $sizesMax = explode(' ', $breakpoints);
        $sizesMax = end($sizesMax);
        $sizesMax = str_replace('w', 'px', $sizesMax);

        $dataSizes = '(max-width: ' . $sizesMax . ') calc(100vw - 20px), ' . $sizesMax;

        foreach ($sizeArray as $breakpoint => $sizes) {
            $srcset[$breakpoint] = $img->size($sizes[0], $sizes[1], $pwImageResizeOptions)->url . ' ' . $breakpoint;
        }

        $needFallbackImage = (stripos($flags, 'noFallbackImage') === false);

        if ($needFallbackImage) {
            $fallbackImg = reset($sizeArray);
            $fallbackImg = $img->size($fallbackImg[0], $fallbackImg[1], $pwImageResizeOptions);
            $fallbackImgSrc = $fallbackImg->url;
        }

        if ($mode === 'srcset') {

            $markup = $srcSetTag . '="' . implode(', ', $srcset) . '" data-sizes="' . $dataSizes . '"';

            if ($needFallbackImage) {
                $markup = 'src="' . $fallbackImgSrc . '" ' . $markup;
            }

        } elseif ($mode === 'bgset') {

            $markup = 'data-bgset="' . implode(', ', $srcset) . '" data-sizes="' . $dataSizes . '"';

            if ($needFallbackImage) {
                $markup = $markup . ' style="background-image: url(' . $fallbackImgSrc . ')"';
            }

        }

        if (!is_null($classes)) {
            $markup .= ' class="' . $classes . '"';
        }

        return $markup;
    }

    /** Get responsive image sizes by name from config data.
     *
     * @param $sizeName
     *
     * @return mixed
     */
    public function getSrcSetSize($sizeName) {
        $imageSets = wire('config')->imageSets;

        return isset($imageSets[$sizeName]) ? $imageSets[$sizeName] : null;
    }


    /**
     * Calculate responsive image sizes based on smallest one, keeping ratio.
     * Example: getSizeArray([[640, 213], null, 1.5, 3])
     * Example: getSizeArray([[640, 213], null, 1.5, [1920, 640]])
     *
     * @param $sizes
     *
     * @return array
     */
    public function getSizeArray($sizes) {

        $baseSize = $sizes[0];

        $breakpoints = explode(' ', $this->breakpoints);

        $sizeArray = array(
            $breakpoints[0] => $baseSize
        );

        for ($i = 1; $i < count($sizes); $i++) {

            // skip null items
            if (is_null($sizes[$i])) {
                continue;
            }

            // check if an array of image width/height or a multiplier is supplied
            if (is_array($sizes[$i])) {

                $imageSizes = $sizes[$i];

                if (is_null($imageSizes[1])) {
                    // if height is null, calculate percentage using width / mobile width
                    $multiplier = $imageSizes[0] / $baseSize[0];
                    $imageSizes[1] = (int)round($baseSize[1] * $multiplier);

                } elseif (is_null($imageSizes[0])) {
                    // if width is null, calculate percentage using height / mobile height
                    $multiplier = $imageSizes[1] / $baseSize[1];
                    $imageSizes[0] = (int)round($baseSize[0] * $multiplier);
                }

                $sizeArray[$breakpoints[$i]] = $imageSizes;

            } else {

                $multiplier = $sizes[$i];

                $sizeArray[$breakpoints[$i]] = array_map(function ($item) use ($multiplier) {
                    return (int)round($item * $multiplier);
                }, $baseSize);
            }
        }

        return $sizeArray;
    }


    /**
     * Save image size sets to global $config->imageSets array.
     *
     * @param HookEvent $event
     *
     * @return void
     */
    public function storeImageSets(HookEvent $event) {

        $config = wire('config');
        $configImageSets = array();
        $imageSets = $this->imageSets;

        if (!is_null($imageSets)) {
            $imageSets = json_decode($imageSets, true);

            foreach ($imageSets as $set => $sizes) {
                $configImageSets[$set] = $this->getSizeArray($sizes);
            }
        }

        $config->imageSets = $configImageSets;
    }

    /**
     * Append lazysizes JavaScript assets to document body.
     *
     * @param HookEvent $event
     */
    public function loadScripts(HookEvent $event) {

        if ($event->object->template == 'admin') {
            return;
        }

        // do not load scripts if no lazysize image is available
        if (strpos($event->return, 'data-bgset') === false && strpos($event->return, 'data-srcset') === false) {
            return;
        }

        $baseUrl = wire('config')->urls->{$this->className} . 'scripts';

        $scripts = <<< HTML
<script src="$baseUrl/picturefill.min.js" async></script>
<script src="$baseUrl/ls.bgset.min.js" async></script>
<script src="$baseUrl/ls.attrchange.min.js" async></script>
<script src="$baseUrl/lazysizes.min.js" async></script>
HTML;

        $event->return = str_replace("</body>", $scripts . PHP_EOL . '</body>', $event->return);
    }

    /**
     * Return an InputfieldWrapper of Inputfields used to configure the class
     *
     * @param array $data Array of config values indexed by field name
     *
     * @return InputfieldWrapper
     *
     */
    public static function getModuleConfigInputfields(array $data) {

        $defaultData = self::getDefaultData();
        $data = array_merge($defaultData, $data);

        $wrapper = new InputfieldWrapper();

        $fieldName = 'breakpoints';
        $f = wire('modules')->get("InputfieldText");
        $f->attr('name', $fieldName);
        $f->label = __('Breakpoints', __FILE__);
        $f->description = __('Breakpoint sizes in pixels, mobile-first.', __FILE__);
        $f->notes = __('Default', __FILE__) . ': ' . '`' . $defaultData[$fieldName] . '`';
        $f->value = !empty($data[$fieldName]) ? $data[$fieldName] : $defaultData[$fieldName];
        $wrapper->add($f);


        $fieldName = 'imageSets';
        $f = wire('modules')->get("InputfieldTextarea");
        $f->attr('name', $fieldName);
        $f->label = __('Image Sets', __FILE__);
        $f->description = __('JSON array of image sizes.', __FILE__);
        $f->value = !empty($data[$fieldName]) ? $data[$fieldName] : $defaultData[$fieldName];
        $wrapper->add($f);

        $fieldName = 'addLazyloadClass';
        $f = wire('modules')->get("InputfieldCheckbox");
        $f->attr('name', $fieldName);
        $f->label = __('Add "lazyload" class', __FILE__);
        $f->notes = __('Add "lazyload" class to image markup automatically. The class can be added manually in template code where needed.', __FILE__);
        $f->attr('checked', (isset($data[$fieldName]) && $data[$fieldName] == '1') ? 'checked' : '');
        $f->columnWidth = 33;
        $wrapper->add($f);

        $fieldName = 'loadScripts';
        $f = wire('modules')->get("InputfieldCheckbox");
        $f->attr('name', $fieldName);
        $f->label = __('Load scripts', __FILE__);
        $f->notes = __('Uncheck to disable loading lazysize JavaScripts (e.g if you would like to load them manually).', __FILE__);
        $f->attr('checked', (isset($data[$fieldName]) && $data[$fieldName] == '1') ? 'checked' : '');
        $f->columnWidth = 33;
        $wrapper->add($f);

        $fieldName = 'useSrcSetAttr';
        $f = wire('modules')->get("InputfieldCheckbox");
        $f->attr('name', $fieldName);
        $f->label = __('Use "srcset" attribute', __FILE__);
        $f->notes = __('Check to add "srcset" tag on images instead of "data-srcset". This allows native srcset functionality in supported browsers.', __FILE__);
        $f->attr('checked', (isset($data[$fieldName]) && $data[$fieldName] == '1') ? 'checked' : '');
        $f->columnWidth = 34;
        $wrapper->add($f);

        return $wrapper;
    }
}
